### ISSUE TITLE
Sign-off documentation: l10n-changesets, release update, Fennec

### ISSUE THREAD

**Issue by Pike** [mozilla-l10n/documentation#202]
While reviewing a patch with nits, I recognized that the documentation doesn't reflect reality as we have it.

For one, the role of Sign-offs on Firefox 4 Android should be clarified. I looked at the sign-off page, and got very confused. Also, on Android, we ship default on beta, as part of geckoview.

The role of `l10n-changesets.json` isn't described, which makes the language about beta and nightly hard to grasp.

The procedure to update sign-offs on release is missing.  More so, the documentation suggests that it doesn't exist.

**Comment by flodolo** [comment]
> For one, the role of Sign-offs on Firefox 4 Android should be clarified. I looked at the sign-off page, and got very confused. Also, on Android, we ship default on beta, as part of geckoview.

Not sure I understand the last part?

As far as I'm concerned, all the references to Firefox for Android in this document should be removed, as I stopped taking sign-offs when we dropped the product from Pontoon. 

But I'm not sure it should be done before we actually drop Fennec and switch to Fenix for good?

> The role of l10n-changesets.json isn't described, which makes the language about beta and nightly hard to grasp.

I think the current explanation is valid without going into details around `l10n-changesets.json`. For example, the current doc would be valid for the previous system, when the build system was reading directly from Elmo.

But, if we want to document the change to release part, we definitely need to mention it.

**Comment by flodolo** [comment]
Ignoring Android for a moment, and looking at the current version of the doc
https://mozilla-l10n.github.io/documentation/products/review/signoffs.html

Where would it make sense to talk about `l10n-changesets.json`? Right after the 3 bullet points at the beginning?

How to update release: 
* Add release to the second graph, all in red.
* Add a subsection "Update to shipping release"

Would that work? I honestly didn't think of document it, because with a 4 release cycle we hardly are going to use it, but I guess it's probably worth having docs about it.

**Comment by flodolo** [comment]
Updated the title because it really bothered me. The document is updated, and it might be missing some info that is not preventing it from being useful.

As said, happy to address the l10n-changeset and release part, but I think Fennec should remain mentioned until we really drop the project from Elmo.
